name: Use GitHub Secret

on:
  push:

jobs:
  demo-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use secret in a safe way
        run: |
          echo "Running a secure task..."
          echo "The secret is being used, but will not be displayed."
          echo "${{ secrets.SECRET }}" | sha256sum > secret_used_hash.txt
          echo "Secret has been hashed and stored."
