name: Use GitHub Secret

on:
  push:

jobs:
  demo-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use secret in a way required by validation
        run: |
          echo "The secret is \${{ secrets.SECRET }}"
